---
title: "My app server"
logfile: /var/log/fuey.log
inspections:
  pings:
    - 
      - 'Google DNS'
      - '8.8.8.8'
    - 
      - 'Localhost'
      - '0.0.0.0'
  vpns:
    -
      - 'VPN 1'
      - '71.1.1.1'
    -
      - 'VPN 2'
      - '9.0.1.2'
  