---
title: "My app server"
logfile: /var/log/fuey.log
notifications:
  -
    - "ping"
    - "Fuey::Log"
  -
    - "snmpwalk"
    - "SNMPWalkLogger"

traces:
  simple_trace:
      -
        - ping:
            name: "Google DNS"
            ip: "8.8.8.8"
        - snmpwalk:
            name: "VPN 1"
            ip: "70.231.17.13"
            community: "public"
            oid: "1.0.9.0.5.9.9.7.121.1.0.1.1.5"
            version: "v1"
